### ISSUE TITLE
Different results with different Ruby versions

### ISSUE THREAD

**Issue by dzschille** [Shopify/theme-check#284]
I use Bitbuckets pipelines to check our theme on every push. Today i saw three different results with Ruby versions 2.7.0 to 2.7.2. This is the build i run:

```
pipelines:
    default:
        - parallel:
            - step:
                name: Run Theme-Kit to check templates and more
                image: ruby:2.7.2
                script:
                    - gem install theme-check
                    - theme-check .
```

This is the result:

```
+ gem install theme-check
Successfully installed liquid-5.0.1
Successfully installed nokogiri-1.11.3-x86_64-linux
Building native extensions. This could take a while...
Successfully installed nokogumbo-2.0.5
Successfully installed theme-check-0.8.1
4 gems installed

+ theme-check .
Checking . ...
sections/timer.liquid:20: style: SpaceInsideBraces: Space missing before '}}'.
	<h1 id="timer-headline" style="color: {{ section.settings.text_color}}">{{ section.settings.title }}</h1>
	                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
168 files inspected, 1 offenses detected, 1 offenses auto-correctable
```

Then i switched the image to ruby:2.7.1 and the result is now:

```
+ gem install theme-check
Successfully installed liquid-5.0.1
Successfully installed nokogiri-1.11.3-x86_64-linux
Building native extensions. This could take a while...
Successfully installed nokogumbo-2.0.5
Successfully installed theme-check-0.8.1
4 gems installed

+ theme-check .
Checking . ...
168 files inspected, 0 offenses detected, 0 offenses auto-correctable
```

An when i switched the image to ruby:2.7.0 theme-check doesn't even work:

```
+ gem install theme-check
Successfully installed liquid-5.0.1
Successfully installed nokogiri-1.11.3-x86_64-linux
Building native extensions. This could take a while...
Successfully installed nokogumbo-2.0.5
Successfully installed theme-check-0.8.1
4 gems installed

+ theme-check .
/usr/local/bundle/gems/liquid-5.0.1/lib/liquid/tokenizer.rb:31:in `split': invalid byte sequence in US-ASCII (ArgumentError)
	from /usr/local/bundle/gems/liquid-5.0.1/lib/liquid/tokenizer.rb:31:in `tokenize'
	from /usr/local/bundle/gems/liquid-5.0.1/lib/liquid/tokenizer.rb:11:in `initialize'
	from /usr/local/bundle/gems/liquid-5.0.1/lib/liquid/parse_context.rb:27:in `new'
	from /usr/local/bundle/gems/liquid-5.0.1/lib/liquid/parse_context.rb:27:in `new_tokenizer'
	from /usr/local/bundle/gems/liquid-5.0.1/lib/liquid/template.rb:110:in `parse'
	from /usr/local/bundle/gems/liquid-5.0.1/lib/liquid/template.rb:97:in `parse'
	from /usr/local/bundle/gems/theme-check-0.8.1/lib/theme_check/template.rb:88:in `parse'
	from /usr/local/bundle/gems/theme-check-0.8.1/lib/theme_check/template.rb:72:in `parse'
	from /usr/local/bundle/gems/theme-check-0.8.1/lib/theme_check/template.rb:80:in `root'
	from /usr/local/bundle/gems/theme-check-0.8.1/lib/theme_check/visitor.rb:12:in `visit_template'
	from /usr/local/bundle/gems/theme-check-0.8.1/lib/theme_check/analyzer.rb:41:in `block in analyze_theme'
	from /usr/local/bundle/gems/theme-check-0.8.1/lib/theme_check/analyzer.rb:41:in `each'
	from /usr/local/bundle/gems/theme-check-0.8.1/lib/theme_check/analyzer.rb:41:in `analyze_theme'
	from /usr/local/bundle/gems/theme-check-0.8.1/lib/theme_check/cli.rb:157:in `check'
	from /usr/local/bundle/gems/theme-check-0.8.1/lib/theme_check/cli.rb:97:in `run!'
	from /usr/local/bundle/gems/theme-check-0.8.1/lib/theme_check/cli.rb:101:in `run'
	from /usr/local/bundle/gems/theme-check-0.8.1/lib/theme_check/cli.rb:119:in `parse_and_run'
	from /usr/local/bundle/gems/theme-check-0.8.1/exe/theme-check:6:in `<top (required)>'
	from /usr/local/bundle/bin/theme-check:23:in `load'
	from /usr/local/bundle/bin/theme-check:23:in `<main>'
Checking . ...
```

To make it even strager: my local computer runs Ubuntu 20.04 with Ruby 2.7.0p0 (2019-12-25 revision 647ee6f091). When i run the theme-check locally i get the second upper result:

```
theme-check .
Checking . ...
168 files inspected, 0 offenses detected, 0 offenses auto-correctable
```

Then i made a test project to where i just copied the file _sections/timer.liquid_ and the _.theme-check.yml_, also taken from the project:

```
ConvertIncludeToRender:
    enabled: false
UndefinedObject:
    enabled: false
LiquidTag:
    enabled: false
ImgWidthAndHeight:
    enabled: false
TemplateLength:
    max_length: 330
MatchingSchemaTranslations:
    enabled: false
RemoteAsset:
    enabled: false
MissingRequiredTemplateFiles:
    enabled: false
RequiredDirectories:
    enabled: false
DefaultLocale:
    enabled: false
```

Now i get the error:

```
theme-check .
Checking . ...
sections/timer.liquid:20: style: SpaceInsideBraces: Space missing before '}}'.
	<h1 id="timer-headline" style="color: {{ section.settings.text_color}}">{{ section.settings.title }}</h1>
	                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

1 files inspected, 1 offenses detected, 1 offenses auto-correctable
```

I have no idea what is happening here. Have you made similar experiences?
