### ISSUE TITLE
Config file support

### ISSUE THREAD

**Issue by macournoyer** [Shopify/theme-check#3]
Similar to a `.rubocop.yml` file. Should allow disabling checks, and tweaking parameters:

`.theme-check.yml`

```yml
IncludeTag:
  enabled: false

TemplateLength:
  max: 100
```
