### ISSUE TITLE
Feature Request - Add flag to filter errors for specific files

### ISSUE THREAD

**Issue by sdn90** [Shopify/theme-check#499]
I think this is a pretty important feature for people who are adding Theme Check to existing themes. The codebase I'm working on has a huge amount of errors and it's not realistic for us to fix everything in one pass.

My ideal situation would be:
`shopify theme check [file1] [file2]`

I think this _should_ work with [lint-staged](https://github.com/okonet/lint-staged) without having to configure too much stuff

**Comment by eloyesp** [comment]
I would expect the whole theme checks to be Enabled, but only report errors for the given files. And if `autofix` is enabled, then autofix should **not** touch any file out of the args.

**Comment by charlespwd** [comment]
I've added partial support for this in [Shopify/theme-check-action](https://github.com/Shopify/theme-check-action). Now that we annotate files, if you have the following configuration, only the diff'ed files will be annotated on your PR:

```
      - name: Theme Check
        uses: shopify/theme-check-action@v1
        with:
          theme_root: '.' # optional, could be './dist'
          token: ${{ github.token }}
          base: main
```

Is that enough for you? 

The approach I used was to use `-o json` option and filter the results after the fact. I didn't go with the CLI argument route because shells typically have a limit of arguments you pass to them. By outputting the list of diffed files to a file, we can avoid the 250 argument limit as well as requiring you to write a complicated pattern that might work.

A `--filter` might still be desirable. But I'm not sure it's _that great_ for this particular use case. Maybe if we let that accept files as input. I'm open to suggestions.
