### ISSUE TITLE
Unused Snippets are not being detected in 1.10.2

### ISSUE THREAD

**Issue by rainerbird** [Shopify/theme-check#573]
I have installed Shopify CLI with Theme Check (version 1.10.2) - and am not getting errors for Unused Snippets.

I have been creating Snippets on purpose in the snippets directory that aren't being used - but when I run 'theme check' I am getting no errors:

`0 offenses detected, 0 offenses auto-correctable`

Am I doing something wrong? I have a `.theme-check.yml` file but it is pretty basic (I am enabling Unused Snippet here just to double check):

```
ignore:
  - _src
  - _schema
  - _sections
  - node_modules/*

# Enable a custom check
ClassPartials:
  enabled: false

UnusedSnippet:
  enabled: true
  severity: error
```

Let me know if there is any other information I can provide to assist with this.
